# Generated by Django 4.2.7 on 2026-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0003_promocodeusage_guest_email_nullable_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="current_usage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total redemptions across all customers (informational only).",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="usage_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum uses per customer (0 for unlimited per customer). Not a global cap.",
            ),
        ),
    ]
