# Generated by Django 4.2.7 on 2025-08-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "orders",
            "0002_order_payment_verified_at_order_paystack_access_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Paystack transaction reference",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in Naira", max_digits=10
                    ),
                ),
                (
                    "amount_kobo",
                    models.IntegerField(help_text="Amount in kobo for Paystack"),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paystack_status",
                    models.CharField(
                        blank=True, help_text="Raw status from Paystack", max_length=50
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True, help_text="Paystack access code", max_length=100
                    ),
                ),
                (
                    "authorization_url",
                    models.URLField(blank=True, help_text="Paystack checkout URL"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer email for payment", max_length=254
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was verified", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
