# Generated by Django 4.2.7 on 2025-08-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Chopsticks and Bowls", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_open", models.BooleanField(default=True)),
                (
                    "delivery_radius_km",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                ("accepts_cash", models.BooleanField(default=True)),
                ("accepts_card", models.BooleanField(default=True)),
                ("accepts_mobile_money", models.BooleanField(default=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="restaurant/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="restaurant/"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.TextField(blank=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Restaurant Settings",
            },
        ),
    ]
