# Generated by Django 4.2.7 on 2025-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_restaurant_settings_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantsettings",
            options={
                "verbose_name": "Restaurant Settings",
                "verbose_name_plural": "Restaurant Settings",
            },
        ),
        migrations.RenameField(
            model_name="restaurantsettings",
            old_name="delivery_radius_km",
            new_name="delivery_radius",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="accepts_card",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="accepts_cash",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="accepts_mobile_money",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="description",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="free_delivery_threshold",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="is_open",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="maintenance_message",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="maintenance_mode",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="minimum_order_amount",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="opening_time",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="twitter_url",
        ),
        migrations.RemoveField(
            model_name="restaurantsettings",
            name="website",
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="minimum_order",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="opening_hours",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="address",
            field=models.TextField(default="Abuja, Nigeria"),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-08-16 18:05:46.322957"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="email",
            field=models.EmailField(
                default="info@chopsticksandbowls.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="name",
            field=models.CharField(default="Chopsticks and Bowls", max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="phone",
            field=models.CharField(default="+234", max_length=20),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default="2025-08-16 18:05:46.322957"
            ),
            preserve_default=False,
        ),
    ]
