# Generated by Django 4.2.7 on 2025-08-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_restaurantsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantsettings",
            name="delivery_fee_base",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                help_text="Base delivery fee",
                max_digits=8,
            ),
        ),
    ]
