# Generated by Django 4.2.7 on 2025-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_restaurantsettings_delivery_fee_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantsettings",
            name="accepts_card",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="accepts_cash",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="accepts_mobile_money",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="description",
            field=models.TextField(
                blank=True, default="Authentic Korean Cuisine in Abuja"
            ),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="restaurant/"),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="free_delivery_threshold",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="instagram_url",
            field=models.URLField(
                blank=True, default="https://instagram.com/chop.sticksandbowls"
            ),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="restaurant/"),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="maintenance_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="meta_keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="tagline",
            field=models.CharField(
                blank=True, default="Authentic Korean Cuisine in Abuja", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="website",
            field=models.URLField(blank=True, default="https://chopsticksandbowls.com"),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="delivery_fee_base",
            field=models.DecimalField(
                decimal_places=2,
                default=2000.0,
                help_text="Base delivery fee",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="delivery_fee_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Additional fee per kilometer",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="name",
            field=models.CharField(default="Chopsticks and Bowls", max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=0.08,
                help_text="VAT rate as decimal (e.g., 0.075 for 7.5%)",
                max_digits=4,
            ),
        ),
    ]
