# Generated by Django 4.2.7 on 2025-08-20 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_restaurant_coordinates"),
        ("core", "0005_restaurantsettings_accepts_card_and_more"),
    ]

    operations = []
