# Generated by Django 4.2.7 on 2025-08-20 13:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_merge_20250820_1437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantsettings",
            name="restaurant_latitude",
            field=models.DecimalField(
                decimal_places=6,
                default=9.082,
                help_text="Restaurant latitude coordinate",
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("4.0"),
                        message="Latitude must be at least 4.0 (Southern Nigeria)",
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("14.0"),
                        message="Latitude must be at most 14.0 (Northern Nigeria)",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="restaurant_longitude",
            field=models.DecimalField(
                decimal_places=6,
                default=7.3986,
                help_text="Restaurant longitude coordinate",
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("2.0"),
                        message="Longitude must be at least 2.0 (Western Nigeria)",
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("15.0"),
                        message="Longitude must be at most 15.0 (Eastern Nigeria)",
                    ),
                ],
            ),
        ),
    ]
