# Generated by ChatGPT on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_restaurantsettings_restaurant_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantsettings",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Primary domain used for business identification (e.g., roschiwater.com)",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="paystack_secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="paystack_public_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="paystack_webhook_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
