# Generated by Django 4.2.7 on 2026-01-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_add_restaurantsettings_paystack_and_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantsettings",
            name="delivery_fee_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=150.0,
                help_text="Additional fee per kilometer",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=0.075,
                help_text="VAT rate as decimal (e.g., 0.075 for 7.5%)",
                max_digits=4,
            ),
        ),
    ]
