# Generated by Django 4.2.7 on 2026-01-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_restaurantsettings_delivery_fee_per_km_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantsettings",
            options={
                "verbose_name": "Business Settings",
                "verbose_name_plural": "Business Settings",
            },
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Frontend domain used for business identification (e.g., roschiwater.com). This is the domain where customers access the website, not the backend API domain. Used to identify which business a request belongs to in a shared backend architecture.",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
