# Generated by Django 4.2.7 on 2026-01-18 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_restaurantsettings_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        help_text="Current status of the quote request",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for admin use"
                    ),
                ),
                (
                    "restaurant_settings",
                    models.ForeignKey(
                        help_text="Business this quote belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="core.restaurantsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Request",
                "verbose_name_plural": "Quote Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_quote_created_3a283a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_quote_status_5a0c80_idx"
                    ),
                    models.Index(
                        fields=["restaurant_settings", "-created_at"],
                        name="core_quote_restaur_281658_idx",
                    ),
                ],
            },
        ),
    ]
