# Generated by Django 4.2.7 on 2026-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_oauth_fields_to_restaurantsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantsettings",
            name="google_oauth_client_id",
            field=models.CharField(
                blank=True,
                help_text="Google OAuth 2.0 Client ID for this business",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="restaurantsettings",
            name="google_oauth_client_secret",
            field=models.CharField(
                blank=True,
                help_text="Google OAuth 2.0 Client Secret for this business",
                max_length=255,
            ),
        ),
    ]
