# Generated by Django 4.2.7 on 2025-08-08 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointstransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("earned", "Earned"),
                    ("spent", "Spent"),
                    ("expired", "Expired"),
                    ("bonus", "Bonus"),
                    ("referral", "Referral Bonus"),
                    ("birthday", "Birthday Bonus"),
                    ("first_order", "First Order Bonus"),
                    ("physical_visit", "Physical Visit"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_code", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_scan", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Loyalty Cards",
            },
        ),
    ]
