# Generated by Django 4.2.7 on 2025-08-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loyalty", "0002_alter_pointstransaction_transaction_type_loyaltycard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltycard",
            name="qr_code",
            field=models.CharField(
                help_text="Customer ID number or LOYALTY- code",
                max_length=255,
                unique=True,
            ),
        ),
    ]
