# Generated by Django 4.2.7 on 2025-08-09 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loyalty", "0003_alter_loyaltycard_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltycard",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_card",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
