# Generated by Django 4.2.7 on 2025-08-19 20:45

from django.db import migrations, models
import loyalty.models


class Migration(migrations.Migration):
    dependencies = [
        ("loyalty", "0004_alter_loyaltycard_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreward",
            name="expires_at",
            field=models.DateTimeField(
                default=loyalty.models.get_default_expiration_date
            ),
        ),
    ]
