# Generated by Django 4.2.7 on 2026-03-30 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _dedupe_loyalty_userpoints_by_user(apps, schema_editor):
    """
    ``UserPoints.user`` was a OneToOneField (unique user_id). This migration
    switches it to ForeignKey; SQLite rebuilds the table and fails if duplicate
    user_id rows exist. Merge duplicates into the lowest-id row per user.
    """
    UserPoints = apps.get_model("loyalty", "UserPoints")
    from collections import defaultdict

    by_user = defaultdict(list)
    for row in UserPoints.objects.all().order_by("id"):
        if row.user_id is None:
            continue
        by_user[row.user_id].append(row)
    for _uid, rows in by_user.items():
        if len(rows) <= 1:
            continue
        keeper = rows[0]
        balance = keeper.balance or 0
        total_earned = keeper.total_earned or 0
        total_spent = keeper.total_spent or 0
        for dup in rows[1:]:
            balance += dup.balance or 0
            total_earned += dup.total_earned or 0
            total_spent += dup.total_spent or 0
            dup.delete()
        keeper.balance = balance
        keeper.total_earned = total_earned
        keeper.total_spent = total_spent
        keeper.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_alter_restaurantsettings_google_oauth_client_id_and_more"),
        (
            "loyalty",
            "0008_rename_loyalty_card_rest_qr_idx_loyalty_loy_restaur_56e763_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(_dedupe_loyalty_userpoints_by_user, migrations.RunPython.noop),
        migrations.AddField(
            model_name="pointstransaction",
            name="restaurant_settings",
            field=models.ForeignKey(
                default=2,
                help_text="Business this transaction belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_transactions",
                to="core.restaurantsettings",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userpoints",
            name="restaurant_settings",
            field=models.ForeignKey(
                default=2,
                help_text="Business this points balance belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_points",
                to="core.restaurantsettings",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userreward",
            name="restaurant_settings",
            field=models.ForeignKey(
                default=2,
                help_text="Business this reward redemption belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_rewards",
                to="core.restaurantsettings",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loyaltycard",
            name="qr_code",
            field=models.CharField(
                help_text="Customer ID number or LOYALTY- code", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="loyaltycard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userpoints",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpoints",
            unique_together={("user", "restaurant_settings")},
        ),
        migrations.AddIndex(
            model_name="pointstransaction",
            index=models.Index(
                fields=["user", "restaurant_settings", "-created_at"],
                name="loyalty_poi_user_id_74d18d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointstransaction",
            index=models.Index(
                fields=["restaurant_settings", "-created_at"],
                name="loyalty_poi_restaur_0cb588_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userpoints",
            index=models.Index(
                fields=["user", "restaurant_settings"],
                name="loyalty_use_user_id_6c38cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userpoints",
            index=models.Index(
                fields=["restaurant_settings", "-balance"],
                name="loyalty_use_restaur_251bf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userreward",
            index=models.Index(
                fields=["user", "restaurant_settings", "-redeemed_at"],
                name="loyalty_use_user_id_b836a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userreward",
            index=models.Index(
                fields=["restaurant_settings", "status"],
                name="loyalty_use_restaur_52a8eb_idx",
            ),
        ),
    ]
