# Generated by Django 4.2.7 on 2026-01-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_restaurantsettings_options_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="businesses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Businesses this user can manage. Superusers can access all businesses.",
                related_name="staff_users",
                to="core.restaurantsettings",
            ),
        ),
    ]
