# Generated by ChatGPT on 2026-01-16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_add_restaurantsettings_paystack_and_domain"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Product size/variant (e.g., '24-pack 35cl', 'Pure Water')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="restaurant_settings",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="core.restaurantsettings",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menuitem",
            name="sku",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Stock Keeping Unit - available quantity",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
