# Generated by Django 4.2.7 on 2026-01-18 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_add_menuitem_size_sku_restaurant_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["category", "sort_order", "name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
