# Generated by Django 4.2.7 on 2026-03-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_category_slug_menuitem_apparel_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("men", "Male"), ("women", "Female"), ("unisex", "Unisex")],
                help_text="Target gender (apparel). Leave blank for food/beverage.",
                max_length=20,
                null=True,
            ),
        ),
    ]
