# Generated by Django 4.2.7 on 2026-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0006_category_restaurant_menuitemimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Legacy: additional image URLs. Prefer MenuItemImage for uploads.",
            ),
        ),
    ]
