# Generated by Django 4.2.7 on 2026-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0010_menuitem_image_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["category", "-created_at", "name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Product barcode (UPC, EAN, or custom QR string).",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
