# Generated by Django 4.2.7 on 2026-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0011_alter_menuitem_options_menuitem_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items/"),
        ),
    ]
