# Generated by Django 4.2.7 on 2026-05-15 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0018_backfill_menuitem_size_from_sizes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="menu_menuit_product_242f34_idx",
            old_name="menu_menuite_product_7e4f1e_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="menu_produc_restaur_70b1f8_idx",
            old_name="menu_produc_restaur_5c8b2d_idx",
        ),
    ]
