# Generated by Django 4.2.7 on 2025-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when payment was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paystack_access_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack access code for transaction",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paystack_reference",
            field=models.CharField(
                blank=True,
                help_text="Paystack transaction reference",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
