# Generated by ChatGPT on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_add_restaurantsettings_paystack_and_domain"),
        ("orders", "0003_change_delivery_address_to_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant_settings",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="core.restaurantsettings",
            ),
            preserve_default=False,
        ),
    ]
