# Generated by Django 4.2.7 on 2026-01-18 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_add_order_restaurant_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
    ]
