# Generated by Django 4.2.7 on 2026-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_add_order_stock_reduced"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant_settings", "-created_at"],
                name="orders_orde_restaur_45a46a_idx",
            ),
        ),
    ]
