# Generated by Django 4.2.7 on 2026-05-15 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="spotlightpost",
            new_name="storefront__restaur_0a47eb_idx",
            old_name="storefront__restaur_8e0f0d_idx",
        ),
    ]
